name: Railway (Staging)

on:
  push:

env:
  RAILWAY_ENV: staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: bash <(curl -fsSL cli.new)
      - run: railway -V
